name: Actividad 1 y 2

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write


    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'
      - name: paso1 - crea entorno virtual
        run: python -m venv venv
      - name: paso2 - activar entorno virtual
        run: ./venv/Scripts/activate   
      - name: paso3 - actualizar pip
        run: pip install --upgrade pip
      - name: paso4 - instalar dependencias
        run: pip install -e .
      - name: paso5 - Ejecutar ingestion
        run: python src/bigdata/ingestion.py 
      - name: paso6 - Ejecutar Auditoria
        run: python src/bigdata/audit_script.py
      - name: paso7 - Ejecutar datos sucios
        run: python src/bigdata/data_sucio.py
      - name: paso8 - Ejecutar Limpieza
        run: python src/bigdata/cleaning.py


      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: generación informe prueba json
          commit_user_name: Valentina Ayala [GitHub Actions]
          commit_user_email: valentina.ayala@est.iudigital.edu.co
          commit_author: Valentina Ayala <valentina.ayala@est.iudigital.edu.co>
